import PDFKit
import SwiftUI

struct ProviderReportGenerator {

    struct ReportData {
        let dateRange: String
        let medication: String
        let dose: String
        let mode: String
        let avgProtein: Int
        let proteinTarget: Int
        let proteinHitRate: Int
        let avgCalories: Int
        let avgWater: Double
        let avgNausea: Double
        let avgEnergy: Double
        let weightStart: Double?
        let weightEnd: Double?
    }

    static func generatePDF(data: ReportData) -> Data {
        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 50

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        return renderer.pdfData { context in
            context.beginPage()

            var y: CGFloat = margin

            // Title
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 24, weight: .light),
                .foregroundColor: UIColor.label
            ]
            let title = "MemoryAisle Weekly Report"
            title.draw(at: CGPoint(x: margin, y: y), withAttributes: titleAttrs)
            y += 36

            // Date range
            let subtitleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 12),
                .foregroundColor: UIColor.secondaryLabel
            ]
            data.dateRange.draw(at: CGPoint(x: margin, y: y), withAttributes: subtitleAttrs)
            y += 30

            // Medication info
            y = drawSection("Medication", at: y, margin: margin)
            y = drawRow("Medication", value: data.medication, at: y, margin: margin, width: pageWidth)
            y = drawRow("Dose", value: data.dose, at: y, margin: margin, width: pageWidth)
            y = drawRow("Mode", value: data.mode, at: y, margin: margin, width: pageWidth)
            y += 16

            // Nutrition
            y = drawSection("Nutrition Summary", at: y, margin: margin)
            y = drawRow("Avg Daily Protein", value: "\(data.avgProtein)g / \(data.proteinTarget)g", at: y, margin: margin, width: pageWidth)
            y = drawRow("Protein Hit Rate", value: "\(data.proteinHitRate)%", at: y, margin: margin, width: pageWidth)
            y = drawRow("Avg Daily Calories", value: "\(data.avgCalories)", at: y, margin: margin, width: pageWidth)
            y = drawRow("Avg Daily Water", value: String(format: "%.1fL", data.avgWater), at: y, margin: margin, width: pageWidth)
            y += 16

            // Symptoms
            y = drawSection("Symptom Summary", at: y, margin: margin)
            y = drawRow("Avg Nausea Level", value: String(format: "%.1f / 5", data.avgNausea), at: y, margin: margin, width: pageWidth)
            y = drawRow("Avg Energy Level", value: String(format: "%.1f / 5", data.avgEnergy), at: y, margin: margin, width: pageWidth)
            y += 16

            // Weight
            if let start = data.weightStart, let end = data.weightEnd {
                y = drawSection("Weight", at: y, margin: margin)
                y = drawRow("Start of Week", value: String(format: "%.1f lbs", start), at: y, margin: margin, width: pageWidth)
                y = drawRow("End of Week", value: String(format: "%.1f lbs", end), at: y, margin: margin, width: pageWidth)
                let change = end - start
                let sign = change >= 0 ? "+" : ""
                y = drawRow("Change", value: "\(sign)\(String(format: "%.1f", change)) lbs", at: y, margin: margin, width: pageWidth)
                y += 16
            }

            // Disclaimer
            y += 20
            let disclaimerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 9),
                .foregroundColor: UIColor.tertiaryLabel
            ]
            let disclaimer = "Generated by MemoryAisle. This report is for informational purposes only and does not constitute medical advice. Always consult your prescriber for medication-related decisions."
            let disclaimerRect = CGRect(x: margin, y: y, width: pageWidth - margin * 2, height: 60)
            disclaimer.draw(in: disclaimerRect, withAttributes: disclaimerAttrs)

            // Footer
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 8),
                .foregroundColor: UIColor.quaternaryLabel
            ]
            let footer = "SLTR Digital LLC  ·  memoryaisle.app"
            footer.draw(at: CGPoint(x: margin, y: pageHeight - margin), withAttributes: footerAttrs)
        }
    }

    // MARK: - Drawing Helpers

    private static func drawSection(_ title: String, at y: CGFloat, margin: CGFloat) -> CGFloat {
        let attrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 14, weight: .semibold),
            .foregroundColor: UIColor.label
        ]
        title.draw(at: CGPoint(x: margin, y: y), withAttributes: attrs)

        let lineY = y + 20
        let path = UIBezierPath()
        path.move(to: CGPoint(x: margin, y: lineY))
        path.addLine(to: CGPoint(x: margin + 200, y: lineY))
        UIColor.separator.setStroke()
        path.lineWidth = 0.5
        path.stroke()

        return lineY + 8
    }

    private static func drawRow(_ label: String, value: String, at y: CGFloat, margin: CGFloat, width: CGFloat) -> CGFloat {
        let labelAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.secondaryLabel
        ]
        let valueAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 11, weight: .medium),
            .foregroundColor: UIColor.label
        ]

        label.draw(at: CGPoint(x: margin, y: y), withAttributes: labelAttrs)

        let valueSize = value.size(withAttributes: valueAttrs)
        value.draw(at: CGPoint(x: width - margin - valueSize.width, y: y), withAttributes: valueAttrs)

        return y + 18
    }
}
